### ISSUE TITLE
Atom editor does not work after plugin installation

### ISSUE THREAD

**Issue by joshuamzm** [utk-se/CodeRibbon#88]
Hi, I saw your project on HN and wanted to give it a try.

I've never used Atom before (vim/IntelliJ user here).

I installed the version available at Flatpak (Atom 1.54.0) and then looked at how to install plugins. I found yours [here](https://atom.io/packages/code-ribbon) and installed it. In the status bar it showed something like "CodeRibbon Welcome Waiting...". I restarted the editor and now I cannot see any pane. Even if I want to open the Preferences view, nothing shows up.

I have done nothing more than what I described here. Clean slate, freshly installed editor+plugin.

Any thoughts? BTW, do you know how can I disable the plugin to make the editor work again?

**Comment by robobenklein** [comment]
This is very possibly the exact same issue that's in #81 which means this isn't at all macos specific.

Although I use flatpaks for other apps myself, I'm not immediately sure how to pass command-line args to atom that way...

If you do find out how to pass `--clear-window-state` to atom via flatpak, let me know simply because I'd like to add that to my testing routine.

If you just want to RM the plugin, Atom normally puts it in `~/.atom/packages/code-ribbon/`.

I'm working my hardest to find the real cause behind the "blank initial window" problem, so hopefully this issue isn't enough to stop you from trying it out again when I do fix it!

**Comment by joshuamzm** [comment]
@robobenklein 

With this command I can execute Atom from the command line, but I think it's not taking the flag correctly, it tries to open the `--clear-window-state` name as a new file.

```shell
flatpak run io.atom.Atom -- --clear-window-state
```

However, I'm able to see panes again! It's weird what happened but now I can test the plugin. Thanks for you reply!

![image](https://user-images.githubusercontent.com/10285345/110202776-8764eb00-7e30-11eb-9545-78bb97c5f72d.png)

**Comment by robobenklein** [comment]
Issue should be fixed as of v0.2.1 ! Thanks for the reports and testing!

Either you can close this or I'll do so once someone else confirms.
