### ISSUE TITLE
Obsidian.md version

### ISSUE THREAD

**Issue by girdzijauskas** [utk-se/CodeRibbon#91]
I think this project is awesome and has a future.

I'm interested in an Obsidian.md (https://obsidian.md) version of this, as the interface I currently default to in Obsidian is essentially 4 patches. Scrolling either side would be absolutely amazing and super intuitive.

I'm a web dev, though with little to none Electron experience / understand of the internals of either Obsidian or CodeRibbon, but this seems like a good thing to play with, that I also want to see happen. So I'm starting some structural investigation on how to port this over.

If anybody is also interested in seeing this happen, I'm happy to join forces at some level. I've got some experience of React + good enough front-end experience, and am willing to stumble through this even if it takes a long amount of time.

**Comment by robobenklein** [comment]
Obsidian.md looks like an awesome tool, but I doubt I could do much to change it without open access to it's source code. I looked briefly but it doesn't appear to be open source? As such I can't offer much advice about how to implement a ribbon view there.

The furthest I could dig was their API included what looked like accessors to the workspace, so if it is electron-based it should certainly be possible. Since it's a paid application, perhaps a feature request to them could carry more weight?

**Comment by girdzijauskas** [comment]
Indeed, I've posted on the Plugin Ideas part of the community as well, https://forum.obsidian.md/t/coderibbon-plugin/17647
